/******************************************************************************/
/*            Generated by IBExpert 2026.4.2.1 21/05/2026 10:40:16            */
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

SET CLIENTLIB 'C:\Program Files (x86)\HK-Software\IBExpert\firebird5\fbclient.dll';

CREATE DATABASE 'C:\Users\Matheus\Desktop\TIConsultoria\ModelTest\DataBase\TESTE.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1252 COLLATION WIN1252;



/******************************************************************************/
/*                                 Generators                                 */
/******************************************************************************/

CREATE GENERATOR GEN_ID_CLIENTS START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_ID_CLIENTS TO 37;

CREATE GENERATOR GEN_ID_OS START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_ID_OS TO 23;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE CLIENTES (
    ID_CLIENTE      INTEGER NOT NULL,
    NOME_CLIENTE    VARCHAR(50),
    CPF_CLIENTE     VARCHAR(18),
    ESTADO_CLIENTE  CHAR(1) NOT NULL
);

CREATE TABLE ORDEM_SERVICO (
    ID_OS       INTEGER NOT NULL,
    ID_CLIENTE  INTEGER NOT NULL,
    DATA_OS     DATE NOT NULL,
    VALOR_OS    NUMERIC(15,2) NOT NULL,
    ESTADO_OS   CHAR(1) NOT NULL
);



/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE CLIENTES ADD PRIMARY KEY (ID_CLIENTE);
ALTER TABLE ORDEM_SERVICO ADD PRIMARY KEY (ID_OS);


/******************************************************************************/
/*                                Foreign keys                                */
/******************************************************************************/

ALTER TABLE ORDEM_SERVICO ADD CONSTRAINT FK_OS_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE) ON DELETE CASCADE;


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/



/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/



/* Trigger: CLIENTES_BI0 */
CREATE OR ALTER TRIGGER CLIENTES_BI0 FOR CLIENTES
ACTIVE BEFORE INSERT POSITION 0
AS
begin
 if (NEW.ID_CLIENTE IS NULL) then
    NEW.ID_CLIENTE = NEXT VALUE FOR GEN_ID_CLIENTS;
end;

/* Trigger: ORDEM_SERVICO_BI */
CREATE OR ALTER TRIGGER ORDEM_SERVICO_BI FOR ORDEM_SERVICO
ACTIVE BEFORE INSERT POSITION 0
AS
begin
if (NEW.ID_OS IS NULL) then
    NEW.ID_OS = next VALUE FOR GEN_ID_OS;
END;