object FormClientesPGTO: TFormClientesPGTO
  Left = 0
  Top = 0
  AutoSize = True
  Caption = 'Formul'#225'rio Clientes'
  ClientHeight = 468
  ClientWidth = 740
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object PainelPrincipal: TPanel
    Left = 0
    Top = 0
    Width = 740
    Height = 417
    Align = alTop
    Color = clSilver
    ParentBackground = False
    TabOrder = 0
    object Label1: TLabel
      Left = 24
      Top = 24
      Width = 66
      Height = 19
      Caption = 'Clientes'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object DBGrid1: TDBGrid
      Left = 24
      Top = 95
      Width = 689
      Height = 305
      DataSource = DataSource
      TabOrder = 0
      TitleFont.Charset = DEFAULT_CHARSET
      TitleFont.Color = clWindowText
      TitleFont.Height = -11
      TitleFont.Name = 'Tahoma'
      TitleFont.Style = []
    end
    object EditFiltroNome: TEdit
      Left = 24
      Top = 56
      Width = 689
      Height = 21
      TabOrder = 1
      TextHint = 'Filtrar Clientes Por Nome'
      OnChange = EditFiltroNomeChange
    end
  end
  object PainelSecundario: TPanel
    Left = 0
    Top = 420
    Width = 740
    Height = 48
    Margins.Left = 20
    Margins.Top = 0
    Margins.Right = 20
    Margins.Bottom = 0
    Align = alBottom
    Color = clGrayText
    ParentBackground = False
    TabOrder = 1
    object BtnDeletar: TButton
      AlignWithMargins = True
      Left = 553
      Top = 1
      Width = 184
      Height = 46
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alLeft
      Caption = 'DELETAR'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 0
      OnClick = BtnDeletarClick
    end
    object BtnAlterar: TButton
      AlignWithMargins = True
      Left = 369
      Top = 1
      Width = 184
      Height = 46
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alLeft
      Caption = 'ALTERAR'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 1
      OnClick = BtnAlterarClick
    end
    object BtnCadastrar: TButton
      AlignWithMargins = True
      Left = 185
      Top = 1
      Width = 184
      Height = 46
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alLeft
      Caption = 'CADASTRAR'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 2
      OnClick = BtnCadastrarClick
    end
    object BtnBuscar: TButton
      AlignWithMargins = True
      Left = 1
      Top = 1
      Width = 184
      Height = 46
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alLeft
      Caption = 'BUSCAR'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 3
      OnClick = BtnBuscarClick
    end
  end
  object DataSource: TDataSource
    DataSet = FDMemTable
    Left = 616
    Top = 8
  end
  object FDMemTable: TFDMemTable
    FetchOptions.AssignedValues = [evMode]
    FetchOptions.Mode = fmAll
    ResourceOptions.AssignedValues = [rvSilentMode]
    ResourceOptions.SilentMode = True
    UpdateOptions.AssignedValues = [uvCheckRequired, uvAutoCommitUpdates]
    UpdateOptions.CheckRequired = False
    UpdateOptions.AutoCommitUpdates = True
    Left = 680
    Top = 8
  end
end
