/******************************************************************************/
/*            Generated by IBExpert 2026.4.2.1 10/07/2026 18:06:00            */
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

SET CLIENTLIB 'C:\Program Files (x86)\Firebird\Firebird_1_5\fbclient.dll';

CREATE DATABASE 'D:\TIConsultoria\DDDOrm\DataBase\TESTE1-5.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1252;



/******************************************************************************/
/*                                  Domains                                   */
/******************************************************************************/

CREATE DOMAIN VALOR AS
NUMERIC(11,3)
DEFAULT 0;

CREATE DOMAIN VALOR2 AS
NUMERIC(11,2)
DEFAULT 0;



/******************************************************************************/
/*                                 Generators                                 */
/******************************************************************************/

CREATE GENERATOR GEN_CODIGO_CLIENTES_PGTO;
SET GENERATOR GEN_CODIGO_CLIENTES_PGTO TO 2;

CREATE GENERATOR GEN_CODIGO_FORMAS_PAGAMENTO;
SET GENERATOR GEN_CODIGO_FORMAS_PAGAMENTO TO 2;

CREATE GENERATOR GEN_COD_PEDIDO;
SET GENERATOR GEN_COD_PEDIDO TO 1;

CREATE GENERATOR GEN_COD_PRODUTOS;
SET GENERATOR GEN_COD_PRODUTOS TO 2;

CREATE GENERATOR GEN_ID_CLIENTS;
SET GENERATOR GEN_ID_CLIENTS TO 0;

CREATE GENERATOR GEN_ID_ITENS_PEDIDOS;
SET GENERATOR GEN_ID_ITENS_PEDIDOS TO 3;

CREATE GENERATOR GEN_ID_OS;
SET GENERATOR GEN_ID_OS TO 0;

CREATE GENERATOR GEN_ID_PEDIDOS;
SET GENERATOR GEN_ID_PEDIDOS TO 2;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE CLIENTES (
    ID_CLIENTE      INTEGER NOT NULL,
    NOME_CLIENTE    VARCHAR(50),
    CPF_CLIENTE     VARCHAR(18),
    ESTADO_CLIENTE  CHAR(1) NOT NULL
);

CREATE TABLE CLIENTES_PGTO (
    CLI_CODIGO          INTEGER NOT NULL,
    CLI_NOME            VARCHAR(60) NOT NULL,
    CLI_ENDERECO        VARCHAR(60) NOT NULL,
    CLI_NUM             VARCHAR(10) NOT NULL,
    CLI_PESSOA          CHAR(1) NOT NULL,
    CLI_DOCUMENTO       VARCHAR(18) NOT NULL,
    CLI_LIMITE_CREDITO  NUMERIC(11,2),
    CLI_ATIVO           CHAR(1) NOT NULL,
    CLI_FONE            BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
    CLI_EMAIL           BLOB SUB_TYPE TEXT SEGMENT SIZE 80
);

CREATE TABLE FORMAS_PAGAMENTO (
    FIN_CODIGO    INTEGER NOT NULL,
    FIN_NOME      VARCHAR(30) NOT NULL,
    FIN_PARCELAS  INTEGER NOT NULL,
    FIN_JUROS     NUMERIC(4,1) NOT NULL
);

CREATE TABLE ITENS_PEDIDO (
    ID_ITEM           INTEGER NOT NULL,
    ID_PEDIDO         INTEGER NOT NULL,
    ID_PRODUTO        INTEGER NOT NULL,
    QUANTIDADE        VALOR NOT NULL,
    PRECO_UNIT        VALOR2 NOT NULL,
    DESCONTO_PERCENT  VALOR2,
    DESCONTO_VALOR    VALOR2,
    TOTAL             VALOR2
);

CREATE TABLE ORDEM_SERVICO (
    ID_OS       INTEGER NOT NULL,
    ID_CLIENTE  INTEGER NOT NULL,
    DATA_OS     DATE NOT NULL,
    VALOR_OS    NUMERIC(15,2) NOT NULL,
    ESTADO_OS   CHAR(1) NOT NULL
);

CREATE TABLE PEDIDOS (
    ID_PEDIDO      INTEGER NOT NULL,
    ID_CLIENTE     INTEGER NOT NULL,
    DATA_EMISSAO   DATE NOT NULL,
    TOTAL_LIQUIDO  VALOR,
    NUMERO_PEDIDO  VARCHAR(13) NOT NULL
);

CREATE TABLE PRODUTOS_ECF (
    PRO_CODIGO         INTEGER NOT NULL,
    PRO_CODIGO_BARRAS  VARCHAR(14),
    PRO_NOME           VARCHAR(50),
    UNI_SIGLA          CHAR(3),
    SIT_PERMITE_VENDA  CHAR(1),
    PRO_ESTOQUE        NUMERIC(18,3),
    PRO_PRECO_VENDA    VALOR,
    ALIQ_PIS           VALOR2,
    ALIQ_COFINS        VALOR2,
    DESCONTO_MAX       VALOR2
);



/******************************************************************************/
/*                             Check constraints                              */
/******************************************************************************/

ALTER TABLE FORMAS_PAGAMENTO ADD CHECK(FIN_PARCELAS > 0);
ALTER TABLE FORMAS_PAGAMENTO ADD CHECK(FIN_JUROS >= 0);


/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE CLIENTES ADD PRIMARY KEY (ID_CLIENTE);
ALTER TABLE CLIENTES_PGTO ADD PRIMARY KEY (CLI_CODIGO);
ALTER TABLE FORMAS_PAGAMENTO ADD PRIMARY KEY (FIN_CODIGO);
ALTER TABLE ITENS_PEDIDO ADD CONSTRAINT PK_ID_ITEM PRIMARY KEY (ID_ITEM);
ALTER TABLE ORDEM_SERVICO ADD PRIMARY KEY (ID_OS);
ALTER TABLE PEDIDOS ADD PRIMARY KEY (ID_PEDIDO);
ALTER TABLE PRODUTOS_ECF ADD CONSTRAINT PK_PRODUTOS_ECF PRIMARY KEY (PRO_CODIGO);


/******************************************************************************/
/*                                Foreign keys                                */
/******************************************************************************/

ALTER TABLE ITENS_PEDIDO ADD CONSTRAINT FK_ID_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS (ID_PEDIDO) ON DELETE CASCADE;
ALTER TABLE ITENS_PEDIDO ADD CONSTRAINT FK_ID_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS_ECF (PRO_CODIGO);
ALTER TABLE ORDEM_SERVICO ADD CONSTRAINT FK_OS_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE) ON DELETE CASCADE;
ALTER TABLE PEDIDOS ADD FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES_PGTO (CLI_CODIGO);


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/



/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/



/* Trigger: BI_CLIENTES_PGTO */
CREATE TRIGGER BI_CLIENTES_PGTO FOR CLIENTES_PGTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    if (NEW.CLI_CODIGO IS NULL) then
    NEW.CLI_CODIGO = GEN_ID(GEN_CODIGO_CLIENTES_PGTO,1);
END;

/* Trigger: BI_FORMAS_PAGAMENTO */
CREATE TRIGGER BI_FORMAS_PAGAMENTO FOR FORMAS_PAGAMENTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    if (NEW.FIN_CODIGO IS NULL) then
        NEW.FIN_CODIGO = GEN_ID(GEN_CODIGO_FORMAS_PAGAMENTO,1);
END;

/* Trigger: BI_ITENS_PEDIDOS */
CREATE TRIGGER BI_ITENS_PEDIDOS FOR ITENS_PEDIDO
ACTIVE BEFORE INSERT POSITION 0
AS
begin
    if (new.ID_ITEM is NULl) then
        new.ID_ITEM = GEN_ID(GEN_ID_ITENS_PEDIDOS,1);
end;

/* Trigger: BI_PEDIDOS */
CREATE TRIGGER BI_PEDIDOS FOR PEDIDOS
ACTIVE BEFORE INSERT POSITION 0
AS
begin
    if (new.ID_PEDIDO is NULl) then
        new.ID_PEDIDO = GEN_ID(GEN_ID_PEDIDOS,1);
end;

/* Trigger: BI_PRODUTOS_EFC */
CREATE TRIGGER BI_PRODUTOS_EFC FOR PRODUTOS_ECF
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    if (new.pro_codigo is null) then
        new.pro_codigo = GEN_ID(GEN_COD_PRODUTOS,1);
END;

/* Trigger: CLIENTES_BI0 */
CREATE TRIGGER CLIENTES_BI0 FOR CLIENTES
ACTIVE BEFORE INSERT POSITION 0
AS
begin
 if (NEW.ID_CLIENTE IS NULL) then
    NEW.ID_CLIENTE = GEN_ID(GEN_ID_CLIENTS,1);
end;

/* Trigger: ORDEM_SERVICO_BI */
CREATE TRIGGER ORDEM_SERVICO_BI FOR ORDEM_SERVICO
ACTIVE BEFORE INSERT POSITION 0
AS
begin
if (NEW.ID_OS IS NULL) then
    NEW.ID_OS = GEN_ID(GEN_ID_OS,1);
END;