/******************************************************************************/
/*            Generated by IBExpert 2026.4.2.1 10/06/2026 10:31:47            */
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

SET CLIENTLIB 'C:\Program Files (x86)\HK-Software\IBExpert\firebird5\fbclient.dll';

CREATE DATABASE 'D:\TIConsultoria\DDDOrm\DataBase\TESTE.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1252 COLLATION WIN1252;



/******************************************************************************/
/*                                 Generators                                 */
/******************************************************************************/

CREATE GENERATOR GEN_CODIGO_CLIENTES_PGTO START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_CODIGO_CLIENTES_PGTO TO 18;

CREATE GENERATOR GEN_CODIGO_FORMAS_PAGAMENTO START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_CODIGO_FORMAS_PAGAMENTO TO 5;

CREATE GENERATOR GEN_ID_CLIENTS START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_ID_CLIENTS TO 37;

CREATE GENERATOR GEN_ID_OS START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_ID_OS TO 23;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE CLIENTES (
    ID_CLIENTE      INTEGER NOT NULL,
    NOME_CLIENTE    VARCHAR(50),
    CPF_CLIENTE     VARCHAR(18),
    ESTADO_CLIENTE  CHAR(1) NOT NULL
);

CREATE TABLE CLIENTES_PGTO (
    CLI_CODIGO          INTEGER NOT NULL,
    CLI_NOME            VARCHAR(60) NOT NULL,
    CLI_ENDERECO        VARCHAR(60) NOT NULL,
    CLI_NUM             VARCHAR(10) NOT NULL,
    CLI_PESSOA          CHAR(1) NOT NULL,
    CLI_DOCUMENTO       VARCHAR(18) NOT NULL,
    CLI_LIMITE_CREDITO  NUMERIC(11,2),
    CLI_ATIVO           CHAR(1) NOT NULL,
    CLI_FONE            BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
    CLI_EMAIL           BLOB SUB_TYPE TEXT SEGMENT SIZE 80
);

CREATE TABLE FORMAS_PAGAMENTO (
    FIN_CODIGO    INTEGER NOT NULL,
    FIN_NOME      VARCHAR(30) NOT NULL,
    FIN_PARCELAS  INTEGER NOT NULL,
    FIN_JUROS     NUMERIC(4,1) NOT NULL
);

CREATE TABLE ORDEM_SERVICO (
    ID_OS       INTEGER NOT NULL,
    ID_CLIENTE  INTEGER NOT NULL,
    DATA_OS     DATE NOT NULL,
    VALOR_OS    NUMERIC(15,2) NOT NULL,
    ESTADO_OS   CHAR(1) NOT NULL
);



/******************************************************************************/
/*                             Check constraints                              */
/******************************************************************************/

ALTER TABLE FORMAS_PAGAMENTO ADD CHECK(FIN_PARCELAS > 0);
ALTER TABLE FORMAS_PAGAMENTO ADD CHECK(FIN_JUROS >= 0);


/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE CLIENTES ADD PRIMARY KEY (ID_CLIENTE);
ALTER TABLE CLIENTES_PGTO ADD PRIMARY KEY (CLI_CODIGO);
ALTER TABLE FORMAS_PAGAMENTO ADD PRIMARY KEY (FIN_CODIGO);
ALTER TABLE ORDEM_SERVICO ADD PRIMARY KEY (ID_OS);


/******************************************************************************/
/*                                Foreign keys                                */
/******************************************************************************/

ALTER TABLE ORDEM_SERVICO ADD CONSTRAINT FK_OS_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE) ON DELETE CASCADE;


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/



/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/



/* Trigger: BI_CLIENTES_PGTO */
CREATE OR ALTER TRIGGER BI_CLIENTES_PGTO FOR CLIENTES_PGTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    if (NEW.CLI_CODIGO IS NULL) then
    NEW.CLI_CODIGO = NEXT VALUE FOR GEN_CODIGO_CLIENTES_PGTO;
END;

/* Trigger: BI_FORMAS_PAGAMENTO */
CREATE OR ALTER TRIGGER BI_FORMAS_PAGAMENTO FOR FORMAS_PAGAMENTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    if (NEW.FIN_CODIGO IS NULL) then
        NEW.FIN_CODIGO = NEXT VALUE FOR GEN_CODIGO_FORMAS_PAGAMENTO;
END;

/* Trigger: CLIENTES_BI0 */
CREATE OR ALTER TRIGGER CLIENTES_BI0 FOR CLIENTES
ACTIVE BEFORE INSERT POSITION 0
AS
begin
 if (NEW.ID_CLIENTE IS NULL) then
    NEW.ID_CLIENTE = NEXT VALUE FOR GEN_ID_CLIENTS;
end;

/* Trigger: ORDEM_SERVICO_BI */
CREATE OR ALTER TRIGGER ORDEM_SERVICO_BI FOR ORDEM_SERVICO
ACTIVE BEFORE INSERT POSITION 0
AS
begin
if (NEW.ID_OS IS NULL) then
    NEW.ID_OS = next VALUE FOR GEN_ID_OS;
END;